# Generated by Django 4.2.4 on 2023-08-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_body_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, db_index=True, upload_to='', verbose_name='Image'),
        ),
    ]
